# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/runsim.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 150, 631, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ch_ignore_blind = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_ignore_blind.setObjectName("ch_ignore_blind")
        self.gridLayout.addWidget(self.ch_ignore_blind, 2, 1, 1, 1)
        self.l_ignore_blind = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_ignore_blind.setObjectName("l_ignore_blind")
        self.gridLayout.addWidget(self.l_ignore_blind, 2, 0, 1, 1)
        self.l_perfect_device = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_perfect_device.setObjectName("l_perfect_device")
        self.gridLayout.addWidget(self.l_perfect_device, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.run_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.run_button.setObjectName("run_button")
        self.gridLayout_2.addWidget(self.run_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 1, 1, 1)
        self.ch_perfect_device = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ch_perfect_device.setObjectName("ch_perfect_device")
        self.gridLayout.addWidget(self.ch_perfect_device, 3, 1, 1, 1)
        self.l_init_cond = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_init_cond.setObjectName("l_init_cond")
        self.gridLayout.addWidget(self.l_init_cond, 1, 0, 1, 1)
        self.l_duration_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.l_duration_2.setObjectName("l_duration_2")
        self.gridLayout.addWidget(self.l_duration_2, 0, 1, 1, 1)
        self.l_duration = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_duration.setObjectName("l_duration")
        self.gridLayout.addWidget(self.l_duration, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_open = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.l_open.setObjectName("l_open")
        self.horizontalLayout_2.addWidget(self.l_open)
        self.b_open = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.b_open.setObjectName("b_open")
        self.horizontalLayout_2.addWidget(self.b_open)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LeoSimRunner"))
        self.ch_ignore_blind.setText(_translate("MainWindow", "CheckBox"))
        self.l_ignore_blind.setText(_translate("MainWindow", "TextLabel"))
        self.l_perfect_device.setText(_translate("MainWindow", "TextLabel"))
        self.run_button.setText(_translate("MainWindow", "RUN"))
        self.ch_perfect_device.setText(_translate("MainWindow", "CheckBox"))
        self.l_init_cond.setText(_translate("MainWindow", "TextLabel"))
        self.l_duration.setText(_translate("MainWindow", "TextLabel"))
        self.b_open.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
